 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - '$_SERVICE_NAME'
   - '--image'
   - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
   - '--region'
   - '$_GCP_REGION'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated'
   - '--update-env-vars=PROJECT_ID=$PROJECT_ID,TOPIC_ID=$_TOPIC_ID'
 images:
 - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'