swagger: "2.0"
info:
  title: banknotes
  description: "Bulk api for scanning bank notes and predicting if real or fake."
  version: "1.0.0"
#host: DNS_NAME_OF_DEPLOYED_API
schemes:
  - "http" # change to https for real workloads
paths:
  "/notes":
    post:
      description: "Submits one or more bank notes for fraud detection."
      operationId: "ingest"
      parameters:
        - in: body
          name: batch
          schema:
            $ref: '#/definitions/Batch'
          examples:
            oneNote:
              summary: Example of a single note
              value: {"subjects": ["my-note-1"], "features": [[0.123,0.234,0.345,0.456]]}   # 4 features per note
            multipleNotes:
              summary: Example of multiple notes
              value: {
                "subjects": ["my-note-1", "my-note-2", "my-note-3"],
                "features": [
                  [0.123,0.234,0.345,0.456],
                  [0.123,0.234,0.345,0.456],
                  [0.123,0.234,0.345,0.456]
                ]
              }
      responses:
        200:
          description: OK
        400:
          description: The input is invalid (e.g. not json or wrong input).
        404:
          description: A user with the specified ID was not found.
        405:
          description: Method was not allowed.
        default:
          description: Unexpected error
definitions:
  Batch:
    properties:
      subjects:
        type: array
        items:
          type: string
      features:
        type: array
        items:
          type: array
          items:
            type: float
    required:
      - subjects
      - features