package models

import (
	"fmt"
	"net/http"
)

/*
Example message to Pub/Sub:
	{
        "subjects": ["dollar", "twenty", "yen", "benjamin", "bitcoin"],
        "features": [[-2.16680,1.59330,0.045122,-1.67800],[1,2,3,4],[-2.8833,1.7713,0.68946,-0.4638],[2.8297,6.3485,-0.73546,-0.58665],[5,6,7,8]]
	}
*/

type Batch struct {
	RequestID string      `json:"request_id,omitempty"` // uuid generated by API
	Subjects  []string    `json:"subjects"`
	Features  [][]float64 `json:"features"`
}

func (b *Batch) Bind(r *http.Request) error {
	fmt.Println("I validated the batch !!!")

	// loop through subjects and features and make sure match and required features match
	if b.Subjects == nil {
		return fmt.Errorf("subjects is a required field")
	}
	if b.Features == nil {
		return fmt.Errorf("features is a required field")
	}
	return nil
}
func (*Batch) Render(w http.ResponseWriter, r *http.Request) error {
	return nil
}
