package models

import (
	"fmt"
	"net/http"
)

/*
Example message to Pub/Sub:
	{
		"batch_id": "UUID-STRING-HERE",
        "subjects": ["dollar", "twenty", "yen", "benjamin", "bitcoin"],
        "features": [[-2.16680,1.59330,0.045122,-1.67800],[1,2,3,4],[-2.8833,1.7713,0.68946,-0.4638],[2.8297,6.3485,-0.73546,-0.58665],[5,6,7,8]]
	}
*/

type Batch struct {
	ID       string      `json:"batch_id,omitempty"` // uuid generated by API
	Subjects []string    `json:"subjects"`
	Features [][]float64 `json:"features"`
}

func (b *Batch) Bind(r *http.Request) error {
	fmt.Println("I validated the batch !!!")

	if len(b.Subjects) <= 0 {
		return fmt.Errorf("subjects must have one or more record")
	}
	if len(b.Features) != len(b.Subjects) {
		return fmt.Errorf("features count must equal subjects")
	}
	for _, sub := range b.Features {
		if len(sub) != 4 {
			return fmt.Errorf("there must be four features per subject")
			break
		}
	}
	return nil
}
func (*Batch) Render(w http.ResponseWriter, r *http.Request) error {
	return nil
}
